#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


wal -R
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color3"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc config border_width 4

killall -q picom
picom --experimental-backend



#Start/Restart Polybar
killall -q polybar 
polybar main &

dunst &
playerctld daemon
#.config/bspwm/1scripts/cleanfullscreen.sh &
